#
# BTstack example 'pan_lwip_http_server' for ESP32 port
#
# Generated by /home/salimterryli/src/btstack/port/esp32
# On Tue May 11 18:28:29 2021

PROJECT_NAME := bnep_ethernet

EXTRA_COMPONENT_DIRS := components

include $(IDF_PATH)/make/project.mk
